# https://github.com/probot/stale#usage

daysUntilStale: 30
daysUntilClose: 7

exemptAssignees: true
exemptLabels:
  - help wanted
  - wontfix

only: issues

staleLabel: stale

markComment: |
  This issue is unconfirmed, and has been labelled as **stale** due to inactivity. It will be closed automatically if no further activity occurs.
  
  A project maintainer can mark an issue as confirmed by adding the **help wanted** label, the **wontfix** label, or an assignee.
