env:
  browser: true
  es2020: true
  webextensions: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
ignorePatterns:
  - lib/
  - node_modules/
rules:
  # Possible Errors
  no-await-in-loop: off
  no-console: off
  no-extra-parens: error
  no-loss-of-precision: warn
  no-promise-executor-return: off
  no-template-curly-in-string: warn
  no-unreachable-loop: warn
  no-useless-backreference: warn
  require-atomic-updates: off
  # Best Practices
  accessor-pairs: warn
  array-callback-return: warn
  block-scoped-var: warn
  class-methods-use-this: warn
  complexity: warn
  consistent-return: warn
  curly: error
  default-case: off
  default-case-last: warn
  default-param-last: warn
  dot-location:
    - error
    - property
  dot-notation: error
  eqeqeq: error
  grouped-accessor-pairs: warn
  guard-for-in: warn
  max-classes-per-file: warn
  no-alert: warn
  no-caller: warn
  no-constructor-return: warn
  no-div-regex: error
  no-else-return: error
  no-empty-function: warn
  no-eq-null: warn
  no-eval: warn
  no-extend-native: warn
  no-extra-bind: error
  no-extra-label: error
  no-floating-decimal: error
  no-implicit-coercion: error
  no-implicit-globals: warn
  no-implied-eval: warn
  no-invalid-this: warn
  no-iterator: warn
  no-labels: warn
  no-lone-blocks: warn
  no-loop-func: warn
  no-magic-numbers: off
  no-multi-spaces: error
  no-multi-str: warn
  no-new: warn
  no-new-func: warn
  no-new-wrappers: warn
  no-octal-escape: warn
  no-param-reassign: warn
  no-proto: warn
  no-restricted-properties: off
  no-return-assign: warn
  no-return-await: warn
  no-script-url: warn
  no-self-compare: warn
  no-sequences: warn
  no-throw-literal: warn
  no-unmodified-loop-condition: warn
  no-unused-expressions: warn
  no-useless-call: warn
  no-useless-concat: warn
  no-useless-return: error
  no-void: warn
  no-warning-comments: warn
  prefer-named-capture-group: warn
  prefer-promise-reject-errors: warn
  prefer-regex-literals: warn
  radix: warn
  require-await: off
  require-unicode-regexp: warn
  vars-on-top: warn
  wrap-iife:
    - error
    - any
  yoda: error
  # Strict Mode
  strict: off
  # Variables
  init-declarations: off
  no-label-var: warn
  no-restricted-globals: off
  no-shadow: warn
  no-undef-init: error
  no-undefined: off
  no-use-before-define: warn
  # Stylistic Issues
  array-bracket-newline: warn
  array-bracket-spacing: warn
  array-element-newline:
    - warn
    - multiline: true
  block-spacing: warn
  brace-style:
    - warn
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - warn
    - properties: never
  capitalized-comments: warn
  comma-dangle:
    - warn
    - always-multiline
  comma-spacing: warn
  comma-style: warn
  computed-property-spacing: warn
  consistent-this: off
  eol-last: warn
  func-call-spacing: warn
  func-name-matching: off
  func-names:
    - warn
    - never
  func-style: warn
  function-call-argument-newline:
    - warn
    - consistent
  function-paren-newline: warn
  id-denylist: off
  id-length: off
  id-match: off
  implicit-arrow-linebreak: warn
  indent:
    - warn
    - 2
    - SwitchCase: 1
      MemberExpression: off
  jsx-quotes: off
  key-spacing: warn
  keyword-spacing: warn
  line-comment-position: warn
  linebreak-style: warn
  lines-around-comment: off
  lines-between-class-members: warn
  max-depth: off
  max-len: off
  max-lines: off
  max-lines-per-function: off
  max-nested-callbacks: off
  max-params: off
  max-statements: off
  max-statements-per-line: warn
  multiline-comment-style: warn
  multiline-ternary: off
  new-cap: warn
  new-parens: warn
  newline-per-chained-call:
    - warn
    - ignoreChainWithDepth: 3
  no-array-constructor: warn
  no-bitwise: warn
  no-continue: warn
  no-inline-comments: warn
  no-lonely-if: warn
  no-mixed-operators: warn
  no-multi-assign: warn
  no-multiple-empty-lines:
    - warn
    - max: 1
  no-negated-condition: warn
  no-nested-ternary: warn
  no-new-object: warn
  no-plusplus: off
  no-restricted-syntax: off
  no-tabs: warn
  no-ternary: off
  no-trailing-spaces: warn
  no-underscore-dangle: warn
  no-unneeded-ternary: warn
  no-whitespace-before-property: warn
  nonblock-statement-body-position: off
  object-curly-newline: warn
  object-curly-spacing: off
  object-property-newline:
    - warn
    - allowAllPropertiesOnSameLine: true
  one-var: off
  one-var-declaration-per-line: off
  operator-assignment: warn
  operator-linebreak: off
  padded-blocks:
    - warn
    - never
  padding-line-between-statements: off
  prefer-exponentiation-operator: warn
  prefer-object-spread: off
  quote-props:
    - warn
    - as-needed
  quotes:
    - warn
    - single
    - avoidEscape: true
  semi: warn
  semi-spacing: warn
  semi-style: warn
  sort-keys: off
  sort-vars: off
  space-before-blocks:
    - warn
    - always
  space-before-function-paren:
    - warn
    - anonymous: never
      named: never
      asyncArrow: always
  space-in-parens: warn
  space-infix-ops: warn
  space-unary-ops: warn
  spaced-comment: warn
  switch-colon-spacing: warn
  template-tag-spacing: off
  unicode-bom: off
  wrap-regex: warn
  # ECMAScript 6
  arrow-body-style: error
  arrow-parens:
    - error
    - as-needed
  arrow-spacing: error
  generator-star-spacing: error
  no-confusing-arrow: error
  no-duplicate-imports: warn
  no-restricted-exports: off
  no-restricted-imports: off
  no-useless-computed-key: error
  no-useless-constructor: warn
  no-useless-rename: error
  no-var: error
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-numeric-literals: off
  prefer-rest-params: warn
  prefer-spread: warn
  prefer-template: error
  rest-spread-spacing: error
  sort-imports: off
  symbol-description: off
  template-curly-spacing: error
  yield-star-spacing: error
globals:
  fakeImport: readonly
