env:
  browser: true
  webextensions: true
  es2020: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 11
rules: {}
globals:
  jQuery: false
  $: false
  moment: false
  fakeImport: true
