name: Documentation issue
description: Missing, incomplete, or unclear documentation
labels: [documentation]
body:
  - type: input
    attributes:
      label: File
      description: Please provide the path or URL to the relevant file and section, if applicable.
      placeholder: i.e. CONTRIBUTING.md or README.md#usage
    validations:
      required: false
  - type: textarea
    attributes:
      label: Details
      placeholder: Describe the problem
    validations:
      required: true
