name: Feature request
description: Propose an enhancement
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Issue guidelines
        - Check the list of open issues before submitting your own to help reduce duplicate issues.
        - If you see your issue already listed, upvote it by adding a :+1: reaction to the initial comment.
        ---
  - type: markdown
    attributes:
      value: |
        Before requesting a feature, please check the following:
        - [Existing issues](https://github.com/AprilSylph/XKit-Rewritten/issues?q=is%3Aissue%20state%3Aopen%20label%3Aenhancement%20OR%20is%3Aissue%20state%3Aclosed%20label%3Aenhancement%20updated%3A%3E%40today-30d)
        - [Excluded features](https://github.com/AprilSylph/XKit-Rewritten/wiki/Excluded-features)
        - [Removed features](https://github.com/AprilSylph/XKit-Rewritten/wiki/Removed-features)

        Not sure if your idea aligns with the project? Start a discussion in the [Suggestion Box](https://github.com/AprilSylph/XKit-Rewritten/discussions/categories/suggestion-box).
  - type: textarea
    attributes:
      label: Description
      description: Please limit your issue to one clearly defined idea. To propose multiple enhancements, open multiple issues.
      placeholder: Describe your idea…
    validations:
      required: true
